name: Benchmark

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

permissions:
  contents: write
  deployments: write

jobs:
  test:
    name: Benchmark on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile
        run: |
          cmake -B build -DKEPLER_BUILD_BENCHMARK=ON -DBUILD_TESTING=OFF .
          cmake --build build --parallel 2

      - name: Check size
        if: ${{ matrix.os != 'windows-latest' }}
        run: build/benchmark/get_simd_size
      - name: Check size (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: build\benchmark\Debug\get_simd_size.exe

      - name: Benchmark
        if: ${{ matrix.os != 'windows-latest' }}
        run: build/benchmark/benchmark | tee benchmark.txt
      - name: Benchmark (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: build\benchmark\Debug\benchmark.exe

      - name: Save benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Kepler benchmarks
          tool: "catch2"
          output-file-path: benchmark.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@dfm"
