name: Benchmark

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  test:
    name: Benchmark on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile
        run: |
          cmake -B build -DBUILD_KEPLER_BENCHMARK=ON -DBUILD_TESTING=OFF .
          cmake --build build --parallel 2

      - name: Check size
        if: ${{ matrix.os != 'windows-latest' }}
        run: build/benchmark/get_simd_size
      - name: Check size (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: build\benchmark\Debug\get_simd_size.exe

      - name: Benchmark
        if: ${{ matrix.os != 'windows-latest' }}
        run: build/benchmark/benchmark
      - name: Benchmark (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: build\benchmark\Debug\benchmark.exe
