name: Benchmark

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  test:
    name: Benchmark on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile
        run: |
          cmake -B build -DBUILD_KEPLER_BENCHMARK=ON .
          cmake --build build --parallel 2
      - name: Benchmark
        if: ${{ matrix.os != 'windows-latest' }}
        run: build/benchmark/benchmark
      - name: Benchmark
        if: ${{ matrix.os == 'windows-latest' }}
        run: build\benchmark\Debug\benchmark.exe
