name: Python tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11"]
        nox-session: ["tests"]
        include:
          - os: macos-latest
            python-version: "3.10"
            nox-session: "tests"
          - os: windows-latest
            python-version: "3.10"
            nox-session: "tests"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install nox
        run: |
          python -m pip install -U pip
          python -m pip install -U nox
      - name: Run tests
        run: python -m nox -f python/noxfile.py --non-interactive -s ${{ matrix.nox-session }}
