name: Test

on:
  push:
    branches:
      - main
      - refactor
    tags:
      - "*"
  pull_request:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build . --parallel 2
      - name: Test
        run: |
          cd build
          ctest --output-on-failure
